GestionTitreFoncierApp/Models/quartier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionTitreFoncierApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quartier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quartier()
        {
            this.tf = new HashSet<tf>();
        }
    
        public int id { get; set; }
        public string libelle { get; set; }
        public bool estlotissement { get; set; }
        public Nullable<int> regionid { get; set; }
        public Nullable<int> user_create { get; set; }
        public Nullable<int> idArr { get; set; }
    
        public virtual Arrondissement Arrondissement { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tf> tf { get; set; }
    }
}

GestionTitreFoncierApp/Controllers/quartiersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionTitreFoncierApp.Models;
using GT.Models;
using GestionTitreFoncierApp.Security;
using PagedList;

namespace GestionTitreFoncierApp.Controllers
{
    [Authorize]
    public class quartiersController : Controller
    {
        private GTFDB_PROD_PRESEntities db = new GTFDB_PROD_PRESEntities();
        public ActionResult getQuarlst(string typ, int? regid)
        {
         

                try
                {
                    if (typ == "Quart")
                    {
                        List<img> lst = new List<img>();
                        img im = null;
                        var quartiers = db.quartier.Where(x => x.estlotissement == false && x.regionid == regid).ToList();
                        for (int j = 0; j < quartiers.Count(); j++)
                        {
                            im = new img();
                            im.pathofimg = quartiers[j].libelle;
                            im.indexnav = quartiers[j].id;
                            lst.Add(im);
                        }

                        SelectList selectsubDirectories = new SelectList(lst, "indexnav", "pathofimg", 0);
                        return Json(selectsubDirectories);
                    }
                    if (typ == "Lotis")
                    {
                        List<img> lst = new List<img>();
                        img im = null;
                        var quartiers = db.quartier.Where(x => x.estlotissement == true && x.regionid == regid).ToList();
                        for (int j = 0; j < quartiers.Count(); j++)
                        {
                            im = new img();
                            im.pathofimg = quartiers[j].libelle;
                            im.indexnav = quartiers[j].id;
                            lst.Add(im);
                        }
                        SelectList selectsubDirectories = new SelectList(lst, "indexnav", "pathofimg", 0);
                        return Json(selectsubDirectories);
                    }
                    else
                    {
                        List<img> lst = new List<img>();
                        img im = null;
                        var quartiers = db.quartier.Where(x => x.regionid == regid).ToList();
                        for (int j = 0; j < quartiers.Count(); j++)
                        {
                            im = new img();
                            im.pathofimg = quartiers[j].libelle;
                            im.indexnav = quartiers[j].id;
                            lst.Add(im);
                        }
                        SelectList selectsubDirectories = new SelectList(lst, "indexnav", "pathofimg", 0);
                        return Json(selectsubDirectories);
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.message = ex.Message;
                    return View("Error");
                }

           
        }

        //public ActionResult getVillelst(int? regid)
        //{


        //        try
        //        {
        //            if (typ == "Quart")
        //            {
        //                List<img> lst = new List<img>();
        //                img im = null;
        //                var quartiers = db.quartiers.Where(x => x.estlotissement == false && x.regionid == regid).ToList();
        //                for (int j = 0; j < quartiers.Count(); j++)
        //                {
        //                    im = new img();
        //                    im.pathofimg = quartiers[j].libelle;
        //                    im.indexnav = quartiers[j].id;
        //                    lst.Add(im);
        //                }

        //                SelectList selectsubDirectories = new SelectList(lst, "indexnav", "pathofimg", 0);
        //                return Json(selectsubDirectories);
        //            }
        //            if (typ == "Lotis")
        //            {
        //                List<img> lst = new List<img>();
        //                img im = null;
        //                var quartiers = db.quartiers.Where(x => x.estlotissement == true && x.regionid == regid).ToList();
        //                for (int j = 0; j < quartiers.Count(); j++)
        //                {
        //                    im = new img();
        //                    im.pathofimg = quartiers[j].libelle;
        //                    im.indexnav = quartiers[j].id;
        //                    lst.Add(im);
        //                }
        //                SelectList selectsubDirectories = new SelectList(lst, "indexnav", "pathofimg", 0);
        //                return Json(selectsubDirectories);
        //            }
        //            else
        //            {
        //                List<img> lst = new List<img>();
        //                img im = null;
        //                var quartiers = db.quartiers.Where(x => x.regionid == regid).ToList();
        //                for (int j = 0; j < quartiers.Count(); j++)
        //                {
        //                    im = new img();
        //                    im.pathofimg = quartiers[j].libelle;
        //                    im.indexnav = quartiers[j].id;
        //                    lst.Add(im);
        //                }
        //                SelectList selectsubDirectories = new SelectList(lst, "indexnav", "pathofimg", 0);
        //                return Json(selectsubDirectories);
        //            }
        //        }
        //        catch (Exception ex)
        //        {
        //            ViewBag.message = ex.Message;
        //            return View("Error");
        //        }

          
        //}


        //GET: quartiers

        public ActionResult getville(int? regid)
        {

            if (regid != 0 /*|| regid != null*/)
            {
                //List<quartier> listquart = new List<quartier>();
                //quartier quart = null;
                //var quartiers = db.quartiers.Where(i => i.Ville.region_ID == regid).ToList(); 
                List<Ville> lst = new List<Ville>();
                Ville vill = null;
                var Villes = db.Ville.Where(x => x.region_ID == regid).ToList();
                for (int j = 0; j < Villes.Count(); j++)
                {
                    vill = new Ville();
                    vill.id = Villes[j].id;
                    vill.libelle = Villes[j].libelle;
                    lst.Add(vill);
                }
                //for (int i = 0; i < quartiers.Count(); i++)
                //{
                //    quart = new quartier();
                //    quart.id = quartiers[i].id;
                //    quart.libelle = quartiers[i].libelle;
                //    listquart.Add(quart);
                //}
                //SelectList selectQuarts = new SelectList(listquart.OrderBy(i => i.libelle), "id", "libelle", 0);
                SelectList selectsubDirectories = new SelectList(lst.OrderBy(i => i.libelle), "id", "libelle", 0);
                return Json(selectsubDirectories);


            }
            SelectList selectsubDirectoriess = new SelectList(db.Ville.OrderBy(i => i.libelle), "id", "libelle");
            return Json(selectsubDirectoriess);

        }
        public ActionResult getquartier(int? ville,int? Arrondi, string typ)
        {
            if(typ== "Quart")
            {
                if (Arrondi == 0 && ville != 0)
                {
                    List<quartier> lst = new List<quartier>();
                    quartier Quartier = null;
                    var Quartiers = db.quartier.Where(x => x.regionid == ville && x.estlotissement == false).ToList();
                    for (int j = 0; j < Quartiers.Count(); j++)
                    {
                        Quartier = new quartier();
                        Quartier.id = Quartiers[j].id;
                        Quartier.libelle = Quartiers[j].libelle;
                        lst.Add(Quartier);
                    }

                    SelectList selectsubDirectories = new SelectList(lst.OrderBy(i=>i.libelle), "id", "libelle", 0);
                    return Json(selectsubDirectories);


                }
                else if (ville == 0 && Arrondi != 0)
                {
                    List<quartier> lst = new List<quartier>();
                    quartier Quartier = null;
                    var Quartiers = db.quartier.Where(x => x.idArr == Arrondi && x.estlotissement == false).ToList();
                    for (int j = 0; j < Quartiers.Count(); j++)
                    {
                        Quartier = new quartier();
                        Quartier.id = Quartiers[j].id;
                        Quartier.libelle = Quartiers[j].libelle;
                        lst.Add(Quartier);
                    }

                    SelectList selectsubDirectories = new SelectList(lst.OrderBy(i => i.libelle), "id", "libelle", 0);
                    return Json(selectsubDirectories);
                }
                else if (ville != 0 && Arrondi != 0)
                {
                    List<quartier> lst = new List<quartier>();
                    quartier Quartier = null;
                    var Quartiers = db.quartier.Where(x => x.idArr == Arrondi && x.regionid == ville && x.estlotissement == false).ToList();
                    for (int j = 0; j < Quartiers.Count(); j++)
                    {
                        Quartier = new quartier();
                        Quartier.id = Quartiers[j].id;
                        Quartier.libelle = Quartiers[j].libelle;
                        lst.Add(Quartier);
                    }

                    SelectList selectsubDirectories = new SelectList(lst.OrderBy(i => i.libelle), "id", "libelle", 0);

GestionTitreFoncierApp/Views/quartiers/Create.cshtml
@model GestionTitreFoncierApp.Models.quartier

@{
    ViewBag.Title = "Create";
}

@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.ui.unobtrusive.js"></script>
@*<link href="~/css/QuartierCss.css" rel="stylesheet" />
<script type="text/javascript" language="javascript">
    $(document).ready(function () {

    });
function validateForm() {
        var isValid = false;
        var nom = $('#libelle').val();


        var reg = $('#' + 'regionid' + ' option:selected').val();
        var url = "/utilisateurs/verfyuserLogin/";
        if (nom == '' || login == null) {
            $('#libelle').css({ 'background-color': 'pink' });
            alert("nom de la location est obligatoire!");
            isValid=false; return isValid;
        }
        else
        {
            $('#libelle').css({ 'background-color': 'white' });
        }


        if (reg == '' || reg == null) {
            alert("Région est obligatoire!");
            $('#regionid').css({ 'background-color': 'pink' });
            isValid = false; return isValid;

        }
        else {
            $('#regionid').css({ 'background-color': 'white' });
        }
        isValid = true;
        return isValid;
}
</script>*@
@*<link href="~/css/utilisateurLabelStyle.css" rel="stylesheet" />*@



@*<div class="panel panel-info" style="height:82%">
    <div class="panel-heading"><left><h3><b>Ajouter Un Location</b></h3></left></div>
    <div class="panel-body">

        <p>
            <a href="/tfs/index" class="btn btn-success btn-sm">
                <span class="glyphicon glyphicon-arrow-left"></span> Retour à l'accueil
            </a>
        </p>*@

        @*@using (Html.BeginForm("create", "quartiers", FormMethod.Post, new { onsubmit = "return validateForm()" }))

        {*@
<div class="row col-md-offset-1" style="margin-right:10px;">
    <div class="col-md-10">
        <form class="form-horizontal" role="form" action="/quartiers/create/" method="post" onsubmit="return validateForm()">

            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <div class="panel panel-success">
                    <div class="panel-heading" style="background-color:#9dacad;">
                        <h3 class="panel-title" style="color:#ffffff;">
                            <b style="text-align:center;">Enregistrement d'une nouvelle localisation</b>
                        </h3>

                    </div>
                    <div class="panel-body">
                        @if (TempData["message"] != null)
            {

                if (TempData["status"].ToString() == "Erreur")
                {
                                <div class="alert-message alert-message-warning">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                    <h4>	<i class="glyphicon glyphicon-ok"></i> Erreur!</h4>
                                    <p> <strong class="text-warning"> @TempData["message"]</strong></p>
                                </div>
                            }
                        }
                       

                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            @Html.Label("Nom du lieu :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.TextBoxFor(model => model.libelle, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.libelle)
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.Label("Est un Lotissement :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.estlotissement)
                                @Html.ValidationMessageFor(model => model.estlotissement)
                            </div>
                        </div>*@
                        <div class="form-group">
                            @Html.Label("Région :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.DropDownList("RegId", null, " --------- Tout -------", htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Ville :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.DropDownList("VilleId", null, " --------- Tout -------", htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group" id="Communes">
                            @Html.Label("Commune :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.DropDownList("CommuneId", null, " --------- Tout -------", htmlAttributes: new { @class = "form-control",@disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group" id="Arrond">
                            @Html.Label("Arrondissement :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.DropDownList("ArrondId", null, " --------- Tout -------", htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group" style="margin-top:15px;">
                            @Html.Label("Type du Lieu :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @*@Html.RadioButton("typLieu", "all", isChecked: true, htmlAttributes: new { @class = "" })<text style="font-size:14px;font-weight:bold">Tout</text>*@
                                @*@Html.RadioButton("typLieu", "Quart", isChecked: true, htmlAttributes: new { @class = "" })<text style="font-size:14px;font-weight:bold">Quartier</text>
                                @Html.RadioButton("typLieu", "Lotis", isChecked: true, htmlAttributes: new { @class = "" })<text style="font-size:14px;font-weight:bold">Lotissement</text>*@
                                <input id="typLieu" name="typLieu" value="Quart" type="radio" checked /> <text>Quartier</text>
                                <input id="typLieu" name="typLieu" value="Lotis" type="radio" /> <text>Lotissement</text>
                            </div>
                        </div>
                        <div class="panel-footer">

                            <button type="submit" class="btn btn-success col-md-offset-5"><span class="glyphicon glyphicon-floppy-save"></span> Enregistrer</button>
                        </div>
                    </div>
                    @*}*@


                </div>
            </div>
        </form>
    </div>
</div>

GestionTitreFoncierApp/Views/quartiers/Delete.cshtml
@model GestionTitreFoncierApp.Models.quartier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>quartier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estlotissement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estlotissement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_create)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_create)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.region.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.region.libelle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestionTitreFoncierApp/Views/quartiers/Details.cshtml
@model GestionTitreFoncierApp.Models.quartier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>quartier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estlotissement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estlotissement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_create)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_create)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.region.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.region.libelle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GestionTitreFoncierApp/Views/quartiers/Edit.cshtml
@model GestionTitreFoncierApp.Models.quartier

@{
    ViewBag.Title = "Edit";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.ui.unobtrusive.js"></script>
<link href="~/css/QuartierCss.css" rel="stylesheet" />

<script type="text/javascript" language="javascript">
    $(document).ready(function () {

    });
function validateForm() {
        var isValid = false;
        var nom = $('#libelle').val();


        var reg = $('#' + 'regionid' + ' option:selected').val();
        var url = "/utilisateurs/verfyuserLogin/";
        if (nom == '' || login == null) {
            $('#libelle').css({ 'background-color': 'pink' });
            alert("nom de la location est obligatoire!");
            isValid=false; return isValid;
        }
        else
        {
            $('#libelle').css({ 'background-color': 'white' });
        }


        if (reg == '' || reg == null) {
            alert("Région est obligatoire!");
            $('#regionid').css({ 'background-color': 'pink' });
            isValid = false; return isValid;

        }
        else {
            $('#regionid').css({ 'background-color': 'white' });
        }
        isValid = true;
        return isValid;
}
</script>
<link href="~/css/utilisateurLabelStyle.css" rel="stylesheet" />



@*<div class="panel panel-info" style="height:82%">
    <div class="panel-heading"><left><h3><b>Modifier un  Location</b></h3></left></div>
    <div class="panel-body">

        <p>
            <a href="/tfs/index" class="btn btn-success btn-xs">
                <span class="glyphicon glyphicon-arrow-left"></span> Retour à l'accueil
            </a>
        </p>*@

@*@using (Html.BeginForm("Edit", "quartiers", FormMethod.Post, new { onsubmit = "return validateForm()" }))

    {*@
<div class="row col-md-offset-1">
    <div class="col-md-10">
        <form class="form-horizontal" role="form" action="/quartiers/edit/" method="post" onsubmit="return validateForm()">

            @Html.AntiForgeryToken()

            @Html.HiddenFor(Model => Model.id)
            <div class="form-horizontal">
                <div class="panel panel-success">
                    <div class="panel-heading" style="background-color:#9dacad;">
                        <h3 class="panel-title" style="color:#ffffff;">
                            <b style="text-align:center;"> Enregistrement d'une nouvelle localisation </b>
                        </h3>

                    </div>
                    <div class="panel-body">


                        @Html.ValidationSummary(true)
                        <div class="form-group">
                            @Html.Label("Nom du lieu :", htmlAttributes: new { @class = "control-label col-md-4" })
                            @*@Html.Label("Nom du lieu :", htmlAttributes: new { @class = "lblFontfamily lblFontsize  control-label col-lg-6" })*@
                            <div class="col-md-3">
                                @Html.TextBoxFor(model => model.libelle, htmlAttributes: new { @class = "form-control" })
                                @*@Html.EditorFor(model => model.libelle)*@
                                @Html.ValidationMessageFor(model => model.libelle)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.Label("Est un Lotissement :", htmlAttributes: new { @class = "control-label col-md-4" })
                            @*@Html.Label("Est un Lotissement:", htmlAttributes: new { @class = "lblFontfamily lblFontsize control-label col-lg-6" })*@
                            <div class="col-md-3">
                                @*@Html.TextBoxFor(model => model.estlotissement, htmlAttributes: new { @class = "form-control" })*@
                                @Html.EditorFor(model => model.estlotissement)
                                @Html.ValidationMessageFor(model => model.estlotissement)
                            </div>
                        </div>





                        <div class="form-group">
                            @Html.Label("Région :", htmlAttributes: new { @class = "control-label col-md-4" })
                            @* @Html.Label("Région:", htmlAttributes: new { @class = "lblFontfamily lblFontsize control-label col-lg-6" })*@
                            <div class="col-md-3">
                                @Html.DropDownList("RegId", null, "..Choisissez une région..", htmlAttributes: new { @class = "form-control select2", style = "width:300px;", required = "required" })
                                @Html.ValidationMessageFor(model => model.regionid)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Ville :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.DropDownList("VilleId", null, " --------- Tout -------", htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group" id="Communes">
                            @Html.Label("Commune :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.DropDownList("CommuneId", null, " --------- Tout -------", htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group" id="Arrond">
                            @Html.Label("Arrondissement :", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-3">
                                @Html.DropDownList("ArrondId", null, " --------- Tout -------", htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                            </div>
                        </div>

                        <div class="panel-footer">

                            <button type="submit" class="btn btn-success col-md-offset-5"><span class="glyphicon glyphicon-floppy-save"></span> Enregistrer</button>
                        </div>
                    </div>
                    @*}*@


                </div>
            </div>
        </form>
    </div>
</div>