GestionTitreFoncierApp/Controllers/saisiesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionTitreFoncierApp.Models;

namespace GestionTitreFoncierApp.Controllers
{
    [Authorize]
    public class saisiesController : Controller
    {
        private GTFDB_PROD_PRESEntities db = new GTFDB_PROD_PRESEntities();
        public ActionResult Index()
        {
            try
            {

               
                    try
                    {
                        ViewBag.user= ViewBag.typelieu = new SelectList(db.utilisateur, "id", "nom"); 
            return View();
                    }
                    catch (Exception ex)
                    {
                        ViewBag.message = ex.Message;
                        return View("Error");
                    }
             
            }
            catch (Exception ex)
            {
                return RedirectToAction("logout", "utilisateurs");

            }
        }
        public ActionResult saisiesview(DateTime? datedu, DateTime? dateau, string user)

        {
            try
            {

              
                    try
                    {
                        List<saisie> lst = new List<saisie>();
            lst = null;
            //saisielst = db.saisies.ToList();
            //ar results = lst;
            if (user != "")//Search saisie For all users
            {
                int cuserid = Convert.ToInt32(user);
                if (datedu != null && dateau != null)
                {
                                        var results = db.saisie.Where(x => x.datesaisie1 >= datedu && x.datesaisie1 <= dateau && x.utilistaurid == cuserid)
                       .Select(y => new
                       {

                           usernom = y.utilisateur.nom,
                           totalSaisieSave = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id && u.typesaisie == 1).Count(),
                           totalSaisieEdit = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id && u.typesaisie == 2).Count(),
                           totalSaisie = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id).Count()
                       }).ToList();
                    return Json(results.Distinct());


                }
                else
                {

                    var results = db.saisie.Where(x => x.utilistaurid == cuserid)
                        .Select(y => new
                        {

                            usernom = y.utilisateur.nom,
                            totalSaisieSave = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id && u.typesaisie == 1).Count(),
                            totalSaisieEdit = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id && u.typesaisie == 2).Count(),
                            totalSaisie = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id).Count()
                        }).ToList();
                    return Json(results.Distinct());


                  
                }
            }
            else
            {
                if (datedu != null && dateau != null)
                {
                    var results = db.saisie.Where(x => x.datesaisie1 >= datedu && x.datesaisie1 <= dateau)
                        .Select(y => new
                        {

                            usernom = y.utilisateur.nom,
                            totalSaisieSave = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id && u.typesaisie == 1).Count(),
                            totalSaisieEdit = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id && u.typesaisie == 2).Count(),
                            totalSaisie = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id).Count()
                        }).ToList();
                    return Json(results.Distinct());


                    
                }
                else
                {
                    int userid;

                    
                var results = db.saisie
                         .Select(y => new
                         {

                             usernom = y.utilisateur.nom,
                             totalSaisieSave = db.saisie.Where(u=>u.utilistaurid==y.utilisateur.id && u.typesaisie==1).Count(),
                             totalSaisieEdit = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id && u.typesaisie == 2).Count(),
                             totalSaisie = db.saisie.Where(u => u.utilistaurid == y.utilisateur.id).Count()
                         }).ToList();
                    return Json(results.Distinct());
                }
            }
        }
                    catch (Exception ex)
                    {
                        ViewBag.message = ex.Message;
                        return View("Error");
    }

            }
            catch (Exception ex)
            {
                return RedirectToAction("logout", "utilisateurs");

            }
        }
        // GET: saisies
        //public ActionResult Index(DateTime ? datedu, DateTime ? dateau, string  user)
        //{
        //    List<utilisateur> saisielst = new List<utilisateur>();
        //    saisielst = db.utilisateurs.ToList();
        //    //if (user!="")//Search saisie For all users
        //    //{
        //    //    if (datedu != null && dateau != null)
        //    //    {    
        //    //        utilisateur ut = new utilisateur();
        //    //        //saisielst = db.saisies.Where(x => x.datesaisie1 > datedu && x.datesaisie1 < dateau).ToList();

        //    //       // saisielst = db.utilisateurs.Where(x => x.id==user).ToList();

        //    //    }
        //    //    else
        //    //    {
        //    //        saisielst = db.utilisateurs.ToList();
        //    //       
        //    //        //IList<SelectListItem> enrgsitmentCount = new List<SelectListItem>
        //    //        // {
        //    //        // new SelectListItem{Text = "California", Value = "B"},
        //    //        // new SelectListItem{Text = "Alaska", Value = "B"},
        //    //        // new SelectListItem{Text = "Illinois", Value = "B"},
        //    //        // new SelectListItem{Text = "Texas", Value = "B"},
        //    //        // new SelectListItem{Text = "Washington", Value = "B"}

        //    //        // };
        //    //    }

        //    //}
        //    //else
        //    //{
        //    //    int userid = Convert.ToInt32(user);
        //    //    if (datedu != null && dateau != null)
        //    //    {

        //    //        saisielst = db.utilisateurs.Where(x => x.id == userid).ToList();
        //    //        ViewBag.countEnregistment = db.saisies.Where(x => x.datesaisie1 > datedu && x.datesaisie1 < dateau && x.typesaisie == 1 && x.utilistaurid == userid).ToList();
        //    //        ViewBag.countmiseajour = db.saisies.Where(x => x.datesaisie1 > datedu && x.datesaisie1 < dateau && x.typesaisie == 2 && x.utilistaurid == userid).ToList();

        //    //    }
        //    //    else
        //    //    {
        //    //        saisielst = db.utilisateurs.Where(x =>x.id == userid).ToList();
        //    //        ViewBag.countEnregistment = db.saisies.Where(x =>x.typesaisie==1 && x.utilistaurid== userid).ToList();
        //    //        ViewBag.countmiseajour = db.saisies.Where(x =>x.typesaisie == 2 && x.utilistaurid == userid).ToList();
        //    //    }
        //    //}

        //    ViewBag.user = ViewBag.typelieu = new SelectList(db.utilisateurs, "id", "nom");
        //    return View(saisielst);
        //}

        // GET: saisies/Details/5
        public ActionResult Details(int? id)
        {
            try
            {

                    try
                    {
                        if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            saisie saisie = db.saisie.Find(id);
            if (saisie == null)
            {
                return HttpNotFound();
            }
            return View(saisie);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.message = ex.Message;
                        return View("Error");
                    }
              
            }
            catch (Exception ex)
            {
                return RedirectToAction("logout", "utilisateurs");

            }
        }

        // GET: saisies/Create
        public ActionResult Create()
        {
            try
            {

                    try
                    {
                        ViewBag.utilistaurid = new SelectList(db.utilisateur, "id", "nom");
            ViewBag.typesaisie = new SelectList(db.typesaisie, "id", "libelle");
            return View();
                    }
                    catch (Exception ex)
                    {
                        ViewBag.message = ex.Message;
                        return View("Error");
                    }
              
            }
            catch (Exception ex)
            {
                return RedirectToAction("logout", "utilisateurs");

            }

        }

        // POST: saisies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,datesaisie,utilistaurid,typesaisie,timesaisie,datesaisie1")] saisie saisie)
        {
            try
            {

                    try
                    {
                        if (ModelState.IsValid)
            {
                db.saisie.Add(saisie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

GestionTitreFoncierApp/Views/saisies/Create.cshtml
@model GestionTitreFoncierApp.Models.saisie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>saisie</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.datesaisie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datesaisie)
                @Html.ValidationMessageFor(model => model.datesaisie)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.utilistaurid, "utilistaurid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("utilistaurid", String.Empty)
                @Html.ValidationMessageFor(model => model.utilistaurid)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typesaisie, "typesaisie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typesaisie", String.Empty)
                @Html.ValidationMessageFor(model => model.typesaisie)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.datesaisie1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datesaisie1)
                @Html.ValidationMessageFor(model => model.datesaisie1)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GestionTitreFoncierApp/Views/saisies/Delete.cshtml
@model GestionTitreFoncierApp.Models.saisie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>saisie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.datesaisie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datesaisie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.timesaisie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timesaisie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datesaisie1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datesaisie1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.utilisateur.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.utilisateur.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typesaisie1.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typesaisie1.libelle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestionTitreFoncierApp/Views/saisies/Details.cshtml
@model GestionTitreFoncierApp.Models.saisie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>saisie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.datesaisie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datesaisie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.timesaisie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timesaisie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datesaisie1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datesaisie1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.utilisateur.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.utilisateur.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typesaisie1.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typesaisie1.libelle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GestionTitreFoncierApp/Views/saisies/Edit.cshtml
@model GestionTitreFoncierApp.Models.saisie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>saisie</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.datesaisie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datesaisie)
                @Html.ValidationMessageFor(model => model.datesaisie)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.utilistaurid, "utilistaurid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("utilistaurid", String.Empty)
                @Html.ValidationMessageFor(model => model.utilistaurid)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typesaisie, "typesaisie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typesaisie", String.Empty)
                @Html.ValidationMessageFor(model => model.typesaisie)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.timesaisie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.timesaisie)
                @Html.ValidationMessageFor(model => model.timesaisie)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datesaisie1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datesaisie1)
                @Html.ValidationMessageFor(model => model.datesaisie1)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GestionTitreFoncierApp/Views/saisies/Index.cshtml
@model IEnumerable<GestionTitreFoncierApp.Models.saisie>

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.ui.unobtrusive.js"></script>
@*<link href="~/css/IndexinfoLableStyle.css" rel="stylesheet" />*@
<script type="text/javascript" language="javascript">

    function btnfunc() {
             var datedu=$('#datedu').val();
        var dateau=$('#dateau').val();
        var user=$('#' + 'user' + ' option:selected').val();
        @*var url = '@Url.Action("DeleteConfirmed", "tfs")?id=' + id;*@
        var url = "/saisies/saisiesview/";
        $.ajax({
            type: "POST",
            url: url,
            data: { datedu: datedu, dateau: dateau, user: user },
            success: function (data) {
                var htmltbl = "<table  class='table table-bordered' style='width:auto;height:auto' border='1px'>" +
                                               "<thead><tr class='info'><th>Utilisateur</th><th>Tout enregistrement</th><th>Tout mise jour</th><th>Tout saisies</th></thead>";
                //var g=
                if (data.length > 1)
                {for (var x = 0; x < data.length; x++)
                   { var b = data.length;
                   if (b > 1)


                       var usernom = "<tr><td><input  id='proprietaires_" + 0 + "__prenom' name='proprietaires[" + 0 + "].prenom'  type='label'  /></td>";
                       var usernom = "<tr><td>" + data[x].usernom + "</td>";

                       var allsave = "<td>"+ data[x].totalSaisieSave+"</td>";

                       var alledit = "<td>"+ data[x].totalSaisieEdit+"</td>";
                       var allsaisies = "<td>"+ data[x].totalSaisie+"</td></tr>";
                       var htmltbl = htmltbl + usernom + allsave + alledit + allsaisies;

                }
                htmltbl += "</table>";
                $('#tblres').html("");
                $('#tblres').html(htmltbl);
                $('#panelhead').css("display","block");
                }

                  else
                  {
                    var usernom = "<tr><td>" + data[0].usernom + "</td>";

                    var allsave = "<td>" + data[0].totalSaisieSave + "</td>";

                    var alledit = "<td>" + data[0].totalSaisieEdit + "</td>";
                    var allsaisies = "<td>" + data[0].totalSaisie + "</td></tr>";
                    var htmltbl = htmltbl + usernom + allsave + alledit + allsaisies;
                    htmltbl += "</table>";
                    $('#tblres').html("");
                    $('#tblres').html(htmltbl);
                    //alert("one");
                  }

            },
            error: function (msg) {
                alert($(this).id);
            }
        });


    }
</script>
<div class="row col-md-offset-1" style="margin-top:50px;margin-right:10px;margin-bottom:80px;">

    <div class="col-md-10">
        <div class="panel panel-default" style="border:hidden;">
            <div class="panel-heading">
                <h1 class="panel-title" style="text-align:center;">Effectuer une Recherche de Saisie</h1>
            </div>
            
               
                    @using (@Html.BeginForm("Index", "saisies", FormMethod.Get))
            {
                        <div class="panel-body">
                            @*<b>Rechercher par:</b>*@
                            <div class="form-horizontal">
                                <div class="col-lg-4">

                                    <div class="form-group">
                                        @Html.Label("Du :", htmlAttributes: new { @class = "lblFontfamily lblFontsize control-label col-md-3", style = "text-align:right; font-family: 'Microsoft Sans Serif', Times;font-size:18px; font-weight: bold;" })
                                        <div class="col-md-8">
                                            <input style="text-align:left;font-size:18px" class="date form-control" id="datedu" name="datedu" type="date" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3">

                                    <div class="form-group">
                                        @Html.Label("Au :", htmlAttributes: new { @class = "lblFontfamily lblFontsize control-label col-md-3", style = "text-align:right; font-family: 'Microsoft Sans Serif', Times;font-size:18px; font-weight: bold;" })
                                        <div class="col-md-9">
                                            <input style="text-align:left;font-size:18px" class="date form-control" id="dateau" name="dateau" type="date" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-5">

                                    <div class="form-group">
                                        @Html.Label("Utilisateur :", htmlAttributes: new { @class = "lblFontfamily lblFontsize control-label col-md-4", style = "text-align:right; font-family: 'Microsoft Sans Serif', Times;font-size:18px; font-weight: bold;" })

                                        <div class="col-md-8" style="text-align:right;" >
                                        @Html.DropDownList("user",null, "..Tout..", htmlAttributes: new { @class = "form-control select2" })
                                            
                                            </div>
                                    </div>
                                </div>
                               
                            </div>

                            </div>
                            <div class="panel-footer">
                                <div class="col-md-offset-5">
                                    <button type="button" class="btn btn-info" onclick='btnfunc()'>
                                        <span class="glyphicon glyphicon-search"></span> Rechercher
                                    </button>
                                </div>
                            </div>
                    }
                       
            </div>
        </div>
    <div class="col-md-10">
            <div class="panel panel-primary" style="border:hidden;">
                <div id="panelhead" class="panel-heading" style="display:none">
                    <h1 class="panel-title" style="text-align:center;">Liste de la recherche</h1>
                </div>
                <div class="panel-body">
                            <table id="tblres" class="table table-bordered">
                                <thead>
                                    <tr class="warning"></tr>
                                </thead>

                            </table>

                        </div>
                    </div>
                </div>
            </div>