GestionTitreFoncierApp/Models/TFSViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GestionTitreFoncierApp.Models
{
    public class TFSViewModel
    {
        public int id { get; set; }
        [Display(Name = "N° de TF:")]
        [Required(ErrorMessage = "Numéro TF est obligatoires !")]
        public int numerotf { get; set; }
        [Display(Name = "Immatriculé le:")]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> datetf { get; set; }
        //[DataType(DataType.Date)]

       
        [Display(Name = "N° ACP:")]

        public string numacp { get; set; }
        [Display(Name = "Date d'opératio:")]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> DateOperation { get; set; }

        [Display(Name = "Valeur du terrain:")]

        public string valeurterrain { get; set; }

        //public Nullable<bool> estbati { get; set; }
        [Display(Name = "Terrain bâti:")]

        public bool estbati { get; set; }

        //[Display(Name = "N° de TF:")]

        public string cheminimage { get; set; }
        [Display(Name = "N° de piéce:")]

        public string numeropiece { get; set; }
        [Display(Name = "N° du Lot:")]

        public string numerolot { get; set; }
        [Display(Name = "nom d'ilot:")]

        public string nomillot { get; set; }
        [Display(Name = "Est un ilot")]

        public bool estillot { get; set; }
        [Display(Name = "Lieu:")]

        public Nullable<int> idquartier { get; set; }
        [Display(Name = "Type du Lieu:")]

        public Nullable<int> typelieu { get; set; }
        [Display(Name = "Type du TF:")]

        public Nullable<int> typetf { get; set; }
        [Display(Name = "N° de TF:")]

        public Nullable<int> typeoperation { get; set; }
        [Display(Name = "Piéce:")]

        public Nullable<int> PIECEJUSTIFICATIVE_id { get; set; }

        

        public Nullable<int> usercreated { get; set; }

        public Nullable<System.DateTime> dateCreated { get; set; }

        public Nullable<int> usermodified { get; set; }

        public Nullable<System.DateTime> dateModified { get; set; }
        [Display(Name = "Superficie:")]

        public string superficie { get; set; }
        public Nullable<int> ID_Unites { get; set; }

        [DataType(DataType.Upload)]
       public HttpPostedFileBase ImageUpload { get; set; }
        [Display(Name = "N° de TF:")]
        public virtual Unites_Surface Unites_Surface { get; set; }

        public virtual piecejustificative piecejustificative { get; set; }
        [Display(Name = "N° de TF:")]

        public virtual quartier quartier { get; set; }
        [Display(Name = "N° de TF:")]

        public virtual typelieu typelieu1 { get; set; }
        [Display(Name = "N° de TF:")]

        public virtual typetf typetf1 { get; set; }
        [Display(Name = "N° de TF:")]
        public Nullable<bool> Actif { get; set; }

        public bool Coopropriete { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<proprietaire> proprietaires { get; set; }
        [Required]
        public virtual List<ProprietaresViewModel> proprietaires { get; set; }
        // public virtual ICollection<ProprietaresViewModel> proprietaires { get; set; }
        //public virtual List<Hypotheque> Hypotheques { get; set; }
        //public virtual List<Mutation> Mutations { get; set; }


    }
}

GestionTitreFoncierApp/Controllers/tfsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionTitreFoncierApp.Models;
using Newtonsoft.Json;
using System.IO;
using GT.Models;
using PagedList.Mvc;
using PagedList;
using System.Globalization;
using System.Linq.Expressions;
using System.Text;
using System.Security;
using System.Web.Security;
using GestionTitreFoncierApp.Security;
using System.Text.RegularExpressions;

namespace GestionTitreFoncierApp.Controllers
{
  [Authorize]
    public class tfsController : Controller
    {
        public GTFDB_PROD_PRESEntities db = new GTFDB_PROD_PRESEntities();
        //public string localphysicpath = @"\\TFSERVER\Domain"; 
        public string localphysicpath = @"c:\Domain\";
        public string PhysicalPath = "C:/Domain/";
        OperationsController OpController = new OperationsController();
        HistoriquesController historique = new HistoriquesController();
        // public string localphysicpath = @"\\ZIAD0Z\Users\ZiAd\Desktop\Domain";
        public ActionResult Acceuil()
        {
            return View();
        }
        public ActionResult viewcleanTF()
        {
            tf tf1 = db.tf.ToList().Last();

            return View("cleanView", tf1);

        }
        [HttpPost]
        public ActionResult viewcleanTF(int? z)
        {

            tf tf1 = (db.tf.ToList().Last());
           // getrealphysicpath(@"\\Ziad0z\Users\ziad\Desktop\Domain", "14126");
            tf1.proprietaire.Clear();
            db.Entry(tf1).State = EntityState.Modified;
            db.SaveChanges();
            db.tf.Remove(tf1);
            db.SaveChanges();
            // return RedirectToAction("Index");

            //return PartialView("imgViewer");
            return View("cleanView", tf1);
        }

        [FiltresAuthorisation(Roles = "Modifier TF,Special")]
        public ActionResult Edit(int? id)
        {
            try
            {
                    string[] strDrives = Environment.GetLogicalDrives();
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    tf tf = db.tf.Find(id);
                    if (tf == null)
                    {
                        return HttpNotFound();
                    }

                    var results = tf.proprietaire.
                        Select(x => new
                        {
                            id = x.id,
                            prenom = x.prenom,
                            nome2 = x.nome2,
                            nom3 = x.nom3,
                            prenommere = x.prenommere,
                            nommere2 = x.nommere2,
                            nommere3 = x.nommere3,
                            lieuNaisance = x.lieuNaisance,
                            dateNaissace = x.dateNaissace,
                            numeropiece = x.numeropiece,
                            piecedateemission = x.piecedateemission,
                            typepiece = x.typepiece,
                            //nationalite = x.nationalite,
                            nomestablishment = x.nomestablishment,
                            typestablishment = x.typestablishment,
                            nomeresponsable1 = x.nomeresponsable1,
                            secturactivite = x.secturactivite,
                            typ = x.typeproprietaire
                            // Checked = db.books.Where(f=>f.id== bid && f.authors == author).Any()  db.books.Any(u=>u.authors==author)
                        }).ToList();


                    var MyViewModel = new TFSViewModel();
                    MyViewModel.id = id.Value;
                    MyViewModel.numerotf = tf.numerotf;
                    MyViewModel.datetf = tf.datetf;
                    MyViewModel.numacp = tf.numacp;
                    MyViewModel.valeurterrain = tf.valeurterrain;
                    MyViewModel.superficie = tf.superficie;
                    MyViewModel.DateOperation = tf.DateOperation;
                MyViewModel.Coopropriete = tf.Coopropriete;
                    MyViewModel.typetf1 = (db.typetf.Where(x => x.id == tf.typetf).FirstOrDefault());
                if(MyViewModel.typetf1 == null)
                {
                    MyViewModel.typetf1 = db.typetf.Find(1);
                }
                    MyViewModel.quartier = (db.quartier.Where(x => x.id == tf.idquartier).FirstOrDefault());
                MyViewModel.Unites_Surface = (db.Unites_Surface.Where(x => x.ID == tf.ID_Unites).FirstOrDefault());
                MyViewModel.piecejustificative = (db.piecejustificative.Where(x => x.id == tf.PIECEJUSTIFICATIVE_id).FirstOrDefault());
                if (MyViewModel.piecejustificative == null)
                {
                    MyViewModel.piecejustificative = db.piecejustificative.Find(4);
                }
                // MyViewModel.quartier.region = (db.quartiers.Where(x => x.id == tf.idquartier.).FirstOrDefault());
                // MyViewModel.quartier = (db.quartiers.Where(x => x.id == tf.idquartier).FirstOrDefault());
                MyViewModel.estbati = tf.estbati;
                    MyViewModel.estillot = tf.estillot;
                    MyViewModel.typelieu = tf.typelieu;
                    MyViewModel.numerolot = tf.numerolot;
                    MyViewModel.nomillot = tf.nomillot;
                    MyViewModel.typelieu = tf.typelieu;
                    MyViewModel.cheminimage = tf.cheminimage;

                    ViewBag.PIECEJUSTIFICATIVE_id = new SelectList(db.piecejustificative, "id", "libelle");
                    ViewBag.idquartier = new SelectList(db.quartier, "id", "libelle");
                ViewBag.ID_Unites = new SelectList(db.Unites_Surface, "ID", "Libelle");
                //ViewBag.typelieu = new SelectList(db.typelieux, "id", "libelle");
                ViewBag.typetf = new SelectList(db.typetf, "id", "libell");
                    //ViewBag.typeproprietaire = db.typetfs.ToList();
                    ViewBag.typeproprietaire = new SelectList(db.typeproprietaire, "id", "libelle");
                    ViewBag.logicallistDrives = strDrives;
                    ViewBag.typelieu = new SelectList(db.typelieu, "id", "libelle");
                    int regid = Convert.ToInt32(tf.quartier.Ville.region.id);
                    int villeid = Convert.ToInt32(tf.quartier.Ville.id);
                    ViewBag.Regid = new SelectList(db.region, "id", "libelle", regid);
                    ViewBag.VilleID = new SelectList(db.Ville.OrderBy(i=>i.libelle), "id", "libelle", villeid);
                   
                    bool typliu = Convert.ToBoolean(tf.quartier.estlotissement);
                    var idquart = 1;
                  if (tf.idquartier != null) {  idquart = Convert.ToInt32(tf.idquartier); }
                    ViewBag.idquartier = new SelectList((db.quartier.Where(x => x.Ville.id == regid && x.estlotissement == typliu).OrderBy(i=>i.libelle).ToList()), "id", "libelle",idquart);
                // prepare for the image 
                ViewBag.ID_Unites = new SelectList(db.Unites_Surface, "ID", "Libelle",tf.ID_Unites);

                string[] imagestf;
                var NTF = Convert.ToString(tf.numerotf);
                var p = getdestpath(NTF);
                string ErrorPath = Server.MapPath(Url.Content("~/Images/ERRORS/"));
                string chemincomplet = "C:/Domain/" + p.Replace(@"\", "/");
                var folder = new DirectoryInfo(chemincomplet);
                if (folder.Exists)
                {
                    if (Directory.GetFiles(chemincomplet).Length == 0 && Directory.GetDirectories(chemincomplet).Length == 0)
                    {
                        imagestf = Directory.GetFiles(ErrorPath);
                    }
                    else
                    { imagestf = Directory.GetFiles(chemincomplet); }
                }
                else
                {
                    imagestf = Directory.GetFiles(ErrorPath);
                }

                byte[] imageByteData2 = System.IO.File.ReadAllBytes(imagestf[0].Replace(@"\", "/"));
                string imageBase64Data2 = Convert.ToBase64String(imageByteData2);
                string imageDataURL2 = string.Format("data:image/jpg;base64,{0}", imageBase64Data2);

                ViewBag.ImageData = imageDataURL2;
                ViewBag.indeximg = 0;
                ViewBag.nbrimages = imagestf.Length - 1;
                TempData["chemins"] = imagestf;

                //string pathofimg1 = returnimagepath(tf.numerotf, "2");
                //var server = db.DriversMappeds.Where(x => x.IsActive == true).FirstOrDefault();
                //string ipadress = server.Domian;
                //string username = server.username;
                //string password = server.Password;
                //string sharedpath = server.SharedPath;
                //int substringsharedpathindex = localphysicpath.Length;
                ////pathofimg1 = @"000 000 à 099 999\010 000 à 019 999\014 000 à 014 999\014 100 à 014 199\DJIB - TF - 14126";
                //string fttppaFTPPATH = pathofimg1.Substring(substringsharedpathindex, pathofimg1.Length - substringsharedpathindex);
                //// fttppaFTPPATH = @"000 000 à 099 999\010 000 à 019 999\014 000 à 014 999\014 100 à 014 199\DJIB-TF-14120";
                //fttppaFTPPATH = getdestpath(tf.numerotf);
                //ftp f = new ftp();
                ////string[] simpleDirectoryListing = f.GetFileList("ftp://" + ipadress + "/" + fttppaFTPPATH, username, password);
                //int countfile = 10;// simpleDirectoryListing.Length;
                //ViewBag.filescount = countfile;

GestionTitreFoncierApp/Views/tfs/List_Coopropriete.cshtml
@using GestionTitreFoncierApp.Helpers
@model IEnumerable < GestionTitreFoncierApp.Models.TF_Cooproprietes>
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-default">
    <div class="panel-heading" style="background-color:#cddedd;">
        <h2 class="panel-title" style="text-align:center;"><strong><b> Coopropriété(s) </b></strong></h2>
    </div>
    <table class="table table-condensed table-striped table-bordered">
        <tr>
            <th>
                @Html.DisplayName("Numero Lot")
            </th>
            <th>
                @Html.DisplayName("Nom du proprietaire")
            </th>
            <th>
                @Html.DisplayName("Superificie du Lot")
            </th>
            <th>
                @Html.DisplayName("Valeur du Lot")
            </th>
            
            <th>
                @*@if (ViewBag.RadiationAnnulationValidationExist == "Oui")
                {
                }
                else
                {*@
                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'>  Nouveau Cooproprietaire</span>", "Nouveau Coopropriete", "Add_Coopropriete", "tfs", routeValues: new { id = ViewBag.ID_TF }, htmlAttributes: new { data_modal = "", @class = "modalCoop btn btn-info pull-right" })
                @*}*@
            </th>
        </tr>
        @if (Model.Count() > 0)
        {

            foreach (var item in Model)
            {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.N_Lot)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Noms_Proprios)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Superficie) @Html.DisplayFor(modelItem => item.Unites_Surface.Libelle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valeur) <sup>FDJ</sup>
                </td>
               
                <td>
                    @*<div class="pull-right">
                        @if (item.Operation.IDStatus == 2 || item.Operation.IDStatus == 3 || (item.Operation.IDStatus == 1 && item.Operation.tempOperation == 1))
                        {
                            if (item.Actif != true)
                            {
                                @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'> Modifier </span>", "Edit", "Edit", "Actes", routeValues: new { id = item.id }, htmlAttributes: new { @class = "modalActe btn btn-primary" })

                                if (item.TypeActe.estobligatoire != 1)
                                {
                                    @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'> Supprimer </span>", "Delete", "Delete", "Actes", routeValues: new { id = item.id }, htmlAttributes: new { @class = "modalActe btn btn-danger" })
                                }
                            }
                        }
                    </div>*@
                </td>
            </tr>
            }
        }
        else
        {
            <tr>
        <td>
            <div class="text-muted">&nbsp;Aucun donnée enregistrée</div>
        </td>
            </tr>
        }
           
</table>
</div>


<script type="text/javascript">


        $(function () {
            $.ajaxSetup({ cache: false });

            $(".modalCoop").on("click", function (e) {
               // alert(" PAGE ACTES");
                // hide dropdown if any (this is used wehen invoking modal from link in bootstrap dropdown )
                //$(e.target).closest('.btn-group').children('.dropdown-toggle').dropdown('toggle');

                $('#saadModalContent').load(this.href, function () {
                   // alert(" saadModalContent load");
                    $('#saadModal').modal({
                        /*backdrop: 'static',*/
                        keyboard: true
                    }, 'show');
                   // alert(" saadModalContent apres show");
                    bindForm(this);
                });
                return false;
            });

        //    $("#idTypeActeur").on("change", function (e) {
        //        alert(" CHOIX ACTEUR");
        //        var select = $("#idTypeActeur");
        //        var url = "/Actes/ChoixTypeActeur/";

        //        select.empty();
        //        $.ajax({
        //            type: "POST",
        //            url: url,
        //            cache: false,
        //            data: false,
        //            success: function (data) {
        //                if (data.length > 0) {
        //                    var markup = "<option value='0'> ---- Selectionnez ----- </option>";
        //                    for (var x = 0; x < data.length; x++) {
        //                        markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
        //                    }
        //                    $("#idTypeActeur").html(markup).show();
        //                }
        //            },
        //            error: function (reponse) {
        //                alert("error : " + reponse);
        //            }

        //        });
        //    });
        });

        function bindForm(dialog) {
            $('form', dialog).submit(function () {
               // alert(" bindForm form");
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            //alert(" bindForm form saadModalContent succes");
                            $('#saadModal').modal('hide');
                            location.reload();
                            $('#ListCoops').load(result.url); //  Load data from the server and place the returned HTML into the matched element


                        } else {
                           // alert(" bindForm form saadModalContent echec");
                            $('#saadModalContent').html(result);
                            bindForm(dialog);
                        }
                    }
                });
                return false;
            });
        }
</script>

GestionTitreFoncierApp/Views/tfs/UploadsImages.cshtml
@{
    ViewBag.Title = "Importations";
}
<div class="row col-md-offset-1" style="margin-right:10px;">
    <div class="col-md-10">
        
            <div class="panel panel-success" style="border:hidden;">
                <div class="panel-heading" style="background-color:#c0d2d3;">
                    <h3 class="panel-title" style="color:#ffffff;">
                        <b>
                            Importation des repertoires d'image des TFs
                        </b>
                    </h3>
                    <span class="pull-right clickables"><i id="ii" class="glyphicon glyphicon-chevron-down shev"></i></span>
                </div>

                @using (Html.BeginForm("UploadsImages", "tfs", FormMethod.Post, new { enctype = "multipart/form-data", name = "new_post" }))
            {
                    <div class="panel-body">
                        @if (TempData["message"] != null)
                {
                    if (TempData["status"].ToString() == "Success")
                    {
                                <div class="alert-message alert-message-success">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                    <h4>	<i class="glyphicon glyphicon-ok"></i> Success!</h4>
                                    <p> <strong> @TempData["message"]</strong></p>
                                </div>
                            }
                            if (TempData["status"].ToString() == "Erreur")
                            {
                                <div class="alert-message alert-message-warning">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                    <h4>	<i class="glyphicon glyphicon-ok"></i> Erreur!</h4>
                                    <p> <strong class="text-warning"> @TempData["message"]</strong></p>
                                </div>
                            }
                        }
                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.Label("Numéros du Titre foncier : ", htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-3">
                                    @Html.TextBox("NumeroTf",null, htmlAttributes: new { @class = "form-control", type="number",required = "required",id= "NumeroTf" })
                               
                                 </div>
                                <div class="col-md-3">
                                    <label id="ReponseExist" class="danger " style="margin-top:10px;"></label>
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Selectionné le repertoire a importer :", htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-6" style="margin-top:5px;">
                                    <div class="input-group">
                                        <input id="Images" class="" type="file" name="Images" multiple="multiple" required/>
                                        @*<div class="input-group-addon" id="PassTrueAP">
                                            <i class="" id="ResultatRepertoires"></i>
                                            @*<span class="glyphicon glyphicon-ok " style="color:seagreen;"></span> Dossier Correct!*@
                                            @*<span class="glyphicon glyphicon-remove " style="color:red;"></span> Dossier Incorrect!
                                        </div>*@
                                    </div>
                                </div>
                            </div>
                         <div class="form-group">
                             <div class = "control-label col-md-8" >
                                 <label id="ReponseType" class="danger " style="margin-top:10px;"></label>
                             </div>
                             
                                @*@Html.Label("Type d'Importations :", htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-6" style="margin-top:5px;">
                                    <input id="TypImport" name="TypImport" value="Folders" type="radio" checked /> <text>Repertoires</text>
                                    <input id="TypImport" name="TypImport" value="Images" type="radio" /> <text>Images</text>
                                </div>*@
                            </div>
                            <input type="hidden" id="TypImport" name="TypImport" value="" />
                        </div>
                        <div class="panel-footer" style="margin:1px 1px 1px 1px;">
                            <button type="submit" class="btn btn-success  col-md-offset-5"> <span class="glyphicon glyphicon-download-alt"></span>  Uploader </button>
                            <button class="btn btn-danger" onclick="Reset()">
                                <span class="glyphicon glyphicon-remove"></span>
                                Réinitialiser
                            </button>
                         </div>
                    </div>
                }



            </div>
        </div>
    <div class="col-md-10" style="">
        <div id="ListeImages" class="row">
            @*<div class="col-xs-3">
                <a href="#" class="thumbnail">
                    <img src="http://placehold.it/350x150" class="img-responsive">
                </a>
            </div>*@
        </div>
    </div>
</div>

<script>
    $("#ReponseExist").hide();

    $('#NumeroTf').on("change", function () {
        var defaults = "";
        $('#ReponseExist').html(defaults);
        $('#ReponseType').html(defaults);
        var t = $(this).val();
        var check = document.getElementById("NumeroTf").value;
        var urlType = "/tfs/VerifiePathExistOfTF";
        if (document.getElementById('NumeroTf').value.length > 0) {
            $.ajax({
                type: "POST",
                url: urlType,
                //url: url,
                dataType: 'json',
                data: { numerotf: t },
                cache: false,
                success: function (data) {
                    if (data.success) {
                        //if (data.success == "Exist") {
                        var str = "";
                        str += "Ce Dossier existe déjà !";
                        $('#ReponseExist').html(str);
                        $('#ReponseExist').css("color", "#0071d7")
                        // .removeClass();
                        document.getElementById("TypImport").value = "Images";
                        var text = "";
                        text += "Ajout d'une nouvelle image au repertoire du Tf existant. "
                        $('#ReponseType').html(text);
                        $('#ReponseType').css("color", "#0071d7");
                        // $('#ReponseExist').addClass('primary');
                        $('#ReponseExist').show();
                        //}
                        var list = "";
                        for (var x = 0; x < data.Filnames.length; x++) {
                            list += "<ul>" + data.Filnames[x].text + "</ul>";
                        }
                        $("#ListeImages").html(list).show();
                      
                    }
                    else {
                        if (data.status == "Inexistant") {

                            var Vide = "";
                            Vide += "Ce Dossier n'existe pas !";
                            $('#ReponseExist').html(Vide);
                            $('#ReponseExist').css("color", "#129b00")
                            $('#ReponseExist').show();
                            document.getElementById("TypImport").value = "Folders";
                            var text = "";
                            text += "Création du nouveau repertoire de ce TF. "
                            $('#ReponseType').html(text);
                            $('#ReponseType').css("color", "#129b00")
                        }
                        else if (data.status == "Numeros Inexistant") {

                            var strr = "";
                            strr += "Ce numeros n'a pas de chemin !";
                            $('#ReponseExist').html(strr);
                            $('#ReponseExist').css("color", "#ff0000")
                            $('#ReponseExist').show();
                            document.getElementById("TypImport").value = "";
                        }
                    }

                },
                error: function (data) {

                }
            });
        }
    });
</script>
<script>
    function Reset() {
        document.getElementById("NumeroTf").value = "";
        $("input[type='file']").val('');
        $("#Images").val('');
    }
</script>
<script>
    $('#NumeroTf').on("change", function () {
        var defaults = "";
        $('#ListeImages').html(defaults);
        var t = $(this).val();
        var check = document.getElementById("NumeroTf").value;
        var urlType1 = "/tfs/GetListImagesFromTF";
        if (document.getElementById('NumeroTf').value.length > 0) {
            $.ajax({
                type: "POST",
                url: urlType1,
                //url: url,
                dataType: 'json',
                data: { numerotf: t },
                cache: false,
                success: function (data) {
                    if (data.success) {
                      
                        var list = '';

                        for (var x = 0; x < data.status.length; x++) {
                            // list += "<ul>" + data.status[x] + "</ul>";
                            list += '<div class="col-md-3">';
                            list += '<a href="" class="">';
                            list += '<label> "'+data.status[x]+'" </label>';
                            list += '</a></div>';
                           // list += '<li>'+data.status[x]+' </li>'
                        }
                        $("#ListeImages").html(list).show();

                    }

                },
                error: function (data) {

                }
            });
        }
    });
</script>